/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MainStopwatchIndexRouteImport } from './routes/_main/stopwatch/index'
import { Route as MainEditorIndexRouteImport } from './routes/_main/editor/index'
import { Route as ApiEditorDocumentsIndexRouteImport } from './routes/api/editor/documents/index'
import { Route as ApiEditorDocumentsIdRouteImport } from './routes/api/editor/documents/$id'
import { Route as MainEditorDocumentsIdRouteImport } from './routes/_main/editor/documents/$id'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStopwatchIndexRoute = MainStopwatchIndexRouteImport.update({
  id: '/stopwatch/',
  path: '/stopwatch/',
  getParentRoute: () => MainRoute,
} as any)
const MainEditorIndexRoute = MainEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => MainRoute,
} as any)
const ApiEditorDocumentsIndexRoute = ApiEditorDocumentsIndexRouteImport.update({
  id: '/api/editor/documents/',
  path: '/api/editor/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditorDocumentsIdRoute = ApiEditorDocumentsIdRouteImport.update({
  id: '/api/editor/documents/$id',
  path: '/api/editor/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MainEditorDocumentsIdRoute = MainEditorDocumentsIdRouteImport.update({
  id: '/editor/documents/$id',
  path: '/editor/documents/$id',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/api/health': typeof ApiHealthRoute
  '/editor/': typeof MainEditorIndexRoute
  '/stopwatch/': typeof MainStopwatchIndexRoute
  '/editor/documents/$id': typeof MainEditorDocumentsIdRoute
  '/api/editor/documents/$id': typeof ApiEditorDocumentsIdRoute
  '/api/editor/documents/': typeof ApiEditorDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/api/health': typeof ApiHealthRoute
  '/': typeof MainIndexRoute
  '/editor': typeof MainEditorIndexRoute
  '/stopwatch': typeof MainStopwatchIndexRoute
  '/editor/documents/$id': typeof MainEditorDocumentsIdRoute
  '/api/editor/documents/$id': typeof ApiEditorDocumentsIdRoute
  '/api/editor/documents': typeof ApiEditorDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_main/': typeof MainIndexRoute
  '/_main/editor/': typeof MainEditorIndexRoute
  '/_main/stopwatch/': typeof MainStopwatchIndexRoute
  '/_main/editor/documents/$id': typeof MainEditorDocumentsIdRoute
  '/api/editor/documents/$id': typeof ApiEditorDocumentsIdRoute
  '/api/editor/documents/': typeof ApiEditorDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/editor/'
    | '/stopwatch/'
    | '/editor/documents/$id'
    | '/api/editor/documents/$id'
    | '/api/editor/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/health'
    | '/'
    | '/editor'
    | '/stopwatch'
    | '/editor/documents/$id'
    | '/api/editor/documents/$id'
    | '/api/editor/documents'
  id:
    | '__root__'
    | '/_main'
    | '/api/health'
    | '/_main/'
    | '/_main/editor/'
    | '/_main/stopwatch/'
    | '/_main/editor/documents/$id'
    | '/api/editor/documents/$id'
    | '/api/editor/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiEditorDocumentsIdRoute: typeof ApiEditorDocumentsIdRoute
  ApiEditorDocumentsIndexRoute: typeof ApiEditorDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/stopwatch/': {
      id: '/_main/stopwatch/'
      path: '/stopwatch'
      fullPath: '/stopwatch/'
      preLoaderRoute: typeof MainStopwatchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/editor/': {
      id: '/_main/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof MainEditorIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/editor/documents/': {
      id: '/api/editor/documents/'
      path: '/api/editor/documents'
      fullPath: '/api/editor/documents/'
      preLoaderRoute: typeof ApiEditorDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editor/documents/$id': {
      id: '/api/editor/documents/$id'
      path: '/api/editor/documents/$id'
      fullPath: '/api/editor/documents/$id'
      preLoaderRoute: typeof ApiEditorDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/editor/documents/$id': {
      id: '/_main/editor/documents/$id'
      path: '/editor/documents/$id'
      fullPath: '/editor/documents/$id'
      preLoaderRoute: typeof MainEditorDocumentsIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainEditorIndexRoute: typeof MainEditorIndexRoute
  MainStopwatchIndexRoute: typeof MainStopwatchIndexRoute
  MainEditorDocumentsIdRoute: typeof MainEditorDocumentsIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainEditorIndexRoute: MainEditorIndexRoute,
  MainStopwatchIndexRoute: MainStopwatchIndexRoute,
  MainEditorDocumentsIdRoute: MainEditorDocumentsIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiEditorDocumentsIdRoute: ApiEditorDocumentsIdRoute,
  ApiEditorDocumentsIndexRoute: ApiEditorDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
